<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;
    
    /**
     * @var string
     */
    protected $title;
    
    /**
     * @var string
     */
    protected $subtitle;
    
    /**
     * @var string
     */
    protected $location;
    
    /**
     * @var string
     */
    protected $keywords;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Get title
     *
     * @return int $title
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * {@inheritdoc}
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }
    
    /**
     * Get subtitle
     *
     * @return int $subtitle
     */
    public function getSubTitle()
    {
        return $this->subtitle;
    }
    
    /**
     * {@inheritdoc}
     */
    public function setSubTitle($subtitle)
    {
        $this->subtitle = $subtitle;
    }
    
    /**
     * Get location
     *
     * @return int $location
     */
    public function getLocation()
    {
        return $this->location;
    }
    
    /**
     * {@inheritdoc}
     */
    public function setLocation($location)
    {
        $this->location = $location;
    }
    
    /**
     * Get keywords
     *
     * @return int $keywords
     */
    public function getKeywords()
    {
        return $this->keywords;
    }
    
    /**
     * {@inheritdoc}
     */
    public function setKeywords($keywords)
    {
        $this->keywords= $keywords;
    }
}
