# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

# Importamos el servicios del bundle creado por nosotros
imports:
    - { resource: '@ApplicationSonataMediaBundle/Resources/config/services.yml' }
    
    
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
