parameters:
    #sonata.media.admin.orm.media.class: Application\Sonata\MediaBundle\Admin\ORM\MediaAdmin  #Hecho para solucionar lo del allow_extra_fields
    #sonata.media.form.type.media.class: Application\Sonata\MediaBundle\Form\Type\MediaType  #Hecho para solucionar lo del allow_extra_fields
    sonata.media.admin.media.class: Application\Sonata\MediaBundle\Admin\MediaAdmin
    
    sonata.media.provider.file.class: Application\Sonata\MediaBundle\Provider\FileProvider
    sonata.media.provider.image.class: Application\Sonata\MediaBundle\Provider\ImageProvider
    sonata.media.provider.dailymotion.class: Application\Sonata\MediaBundle\Provider\DailyMotionProvider
    sonata.media.provider.youtube.class: Application\Sonata\MediaBundle\Provider\YouTubeProvider
    sonata.media.provider.vimeo.class: Application\Sonata\MediaBundle\Provider\VimeoProvider
    sonata.media.dependencyinjection.class: Application\Sonata\MediaBundle\DependencyInjection\SonataMediaExtension
    sonata.media.provider.audio.class: Application\Sonata\MediaBundle\Provider\AudioProvider


#services:
#    sonata.media.provider.audio:
#        class: Application\Sonata\MediaBundle\Provider\AudioProvider
#        arguments:
#            - sonata.media.provider.audio
#            - @sonata.media.filesystem.local
#            - @sonata.media.cdn.server
#            - @sonata.media.generator.default
#            - @sonata.media.thumbnail.format
#            - []
#            - []
#            - @sonata.media.adapter.image.gd
#            - @sonata.media.metadata.proxy
#        tags:
#            - { name: sonata.media.provider }
#        calls:
#            - [ setTemplates, [ { helper_thumbnail: SonataMediaBundle:Provider:thumbnail.html.twig, helper_view: SonataMediaBundle:Provider:view_youtube.html.twig } ] ]

sonata_media:
    pixlr:
        enabled:  true
        secret:   theSecretHash
        referrer: Pixlr Advanced Editor
    # if you don't use default namespace configuration
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
                - sonata.media.provider.audio

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        tv:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.vimeo

            formats:
                cinema:     { width: 1850 , quality: 768}
                grandmatv:  { width: 640 , quality: 480}

        news:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 500 , quality: 90}
        sonata_collection:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/
            #path: /multimedia/web/uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    providers:
        image:
            resizer: sonata.media.resizer.square
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'mp3']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', 'audio/mpeg']
#        audio:
#            allowed_extensions: ['mp3', 'acc', 'vorbis', 'opus']
#            allowed_mime_types: ['audio/mpeg']

#        video:
#            allowed_extensions: ['VP8', 'H.264', 'VP9']
#            allowed_mime_types: ['audio/mpeg']
            
